name: Deploy to GCP
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/365206252904/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-deployer-59@project-9272ed72-1204-49af-a85.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Sync to GCS'
        run: |
          gcloud storage rsync ./www gs://test-bucket-114514 \
            --recursive \
            --delete-unmatched-destination-objects \
            --cache-control="no-cache, max-age=0"
