name: Deploy to GCP
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' 
    steps:
      - uses: actions/checkout@v3
     - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/365206252904/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-deployer-59@project-9272ed72-1204-49af-a85.iam.gserviceaccount.com'
      - name: 'Upload to GCS'
        run: |-
          gcloud storage rsync ./www gs://test-bucket-114514 --recursive
